# Generated by Django 4.2.6 on 2023-10-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('case_number', models.CharField(max_length=255, unique=True, verbose_name='Case Number')),
                ('address', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('case_number', models.CharField(max_length=255, verbose_name='Case Number')),
                ('status', models.CharField(choices=[('PROCESSING', 'PROCESSING'), ('DONE', 'DONE')], max_length=255, unique=True, verbose_name='Status')),
            ],
        ),
    ]
