# Generated by Django 4.2.6 on 2023-10-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=255, verbose_name='Case Number')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
            ],
        ),
    ]
